Javi
NETSERV-UAH/den2ne-Alg pull request #2
Opened 2021-07-15 13:31 UTC by JavierDiazF

El método lo he llamado saveGraph() y mediante la función json.dumps de la librería json lo transforma en formato json.
Después para la prueba llamo al método al final del main ya que no sabía donde ponerlo, y el fichero donde lo crea es el prueba.json

2021-07-19 10:02 UTC, davidcawork commented
Hola javi, te he comentado los cambios sobre el desarrollo que llevaste a cabo 😄 

Un trabajo increible, muchas gracias!

2021-07-19 10:03 UTC, davidcawork commented on src/graph/graph.py
> +
En todos los métodos nuevos que crees, añade una docstring, en la cual comentes que hace ese método.

Así las funciones están comentadas y alguien que venga desde fuera puede saber mejor que hace cada cosa

2021-07-19 10:08 UTC, davidcawork requested changes

2021-07-19 10:08 UTC, davidcawork commented on src/main.py
> +    G.saveGraph('prueba.json')
Meter esta prueba en la función de ``usage()``

2021-07-19 10:08 UTC, davidcawork commented on src/graph/graph.py
> +    def saveGraph(self, path):
En todos los métodos nuevos que crees, añade una docstring, en la cual comentes que hace ese método.

Así las funciones están comentadas y alguien que venga desde fuera puede saber mejor que hace cada cosa

2021-07-19 10:08 UTC, davidcawork commented on src/graph/graph.py
> +            obj_json = json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4)
Tratar de meter las IDs en una única linea para que el json resultante no sea intratable

2021-07-19 10:08 UTC, davidcawork commented on src/graph/graph.py
> +    def saveGraph(self, path):
Añadir el metodo inverso para crear un Obj apartir de un json

2021-07-19 10:08 UTC, davidcawork commented on src/graph/graph.py
>  class Graph(object):
Con el método inverso comprobar si nos pasan un path a un json, para conformar un obj.

Meter un if y si json_path is none, aplicar la lógica ya existente en el constructor de la clase. En caso contrario, si nos pasan un json, damos prioridad a conformar el obj desde el json

2021-07-22 08:47 UTC, JavierDiazF reviewed
Ya he añadido el método para crear el grafo a partir el JSON, y modificado el método de guardar el grafo en el JSON para conseguir un archivo mucho más manejable

2021-07-26 08:09 UTC, davidcawork reviewed
Lo he estado probando un rato y todo perfecto! Solo queda que mires lo que te he puesto de las docstrings

2021-09-01 09:48 UTC, davidcawork approved these changes

2021-09-01 09:49 UTC, merged